### PR TITLE
Added `CPUStatic` backend and implemented new `initialparameters` interface.

### LINKED ISSUE #18: `initialparameters` should return `NeuralNetworkParameters` instead of `NamedTuple`
Relevant section:
https://github.com/JuliaGNI/AbstractNeuralNetworks.jl/blob/2657df1cb34ebec4e4ca36b9c8044965e3dff3d7/src/chain.jl#L49-L53

This change will however most likely be breaking for `GeometricMachineLearning` and `AbstractNeuralNetworks`.

### LINKED ISSUE #19: Redefine `initialparameters` interface.
`initialparameters` should have five input arguments:
1. `rng`
2. `initializer`
3. `model`
4. `backend`
5. `type`

There shouldn't be any other methods! The default should be taken care of by `NeuralNetwork`.

### PR DESCRIPTION
**Pull request by benedict-96**
`CPUStatic` was added as a `Backend`.

Further changes:
- `AbstractInitializer` was renamed to `Initializer`.
- `init` keyword was renamed to `initializer`.
- `initialparameters` now always takes five input arguments: `rng`, `initializer`, `model`, `backend`, `type`.

This pr is breaking for [`GeometricMachineLearning`](https://github.com/JuliaGNI/GeometricMachineLearning.jl) and [`SymbolicNeuralNetworks`](https://github.com/JuliaGNI/SymbolicNeuralNetworks.jl) and should therefore be released as `v0.5`.

Fixes https://github.com/JuliaGNI/AbstractNeuralNetworks.jl/issues/18.
Fixes https://github.com/JuliaGNI/AbstractNeuralNetworks.jl/issues/19.

### CODE REVIEW

**Comment by michakraus** [comment]
Should `CPUStatic` be defined as a subtype of `KernelAbstractions.Backend` ?
```
struct CPUStatic <: KernelAbstractions.Backend end
```
My understanding was that this is considered a mild form of type piracy.

**Comment by benedict-96** [comment]
> Should `CPUStatic` be defined as a subtype of `KernelAbstractions.Backend` ?
> 
> ```
> struct CPUStatic <: KernelAbstractions.Backend end
> ```
> 
> My understanding was that this is considered a mild form of type piracy.

Ok, I see I shouldn't have opened this pr that quickly ...

It is true that in the `KernelAbstractions` documentation it says (somewhere) that custom `Backend`s should only be defined for custom array types, and `MArray` does not constitute such a custom array type. From a pure Julia perspective the following extensions do however not constitute type piracy:
- `KernelAbstractions.ones(::CPUStatic, ::Type{T}, dims::Tuple) where T`
- `KernelAbstractions.zeros(::CPUStatic, ::Type{T}, dims::Tuple) where T`
- `KernelAbstractions.allocate(::CPUStatic, ::Type{T}, dims::Tuple) where T`
- `KernelAbstractions.copyto!(::CPUStatic, x::MArray, y::AbstractArray)`

The only real case of type piracy is:
- `KernelAbstractions.get_backend(::MArray)`

If the `get_backend` type piracy issue is too big, we could solve it by:
1. Defining a new backend type, something like `AbstractNeuralNetworks.NeuralNetworkBackend`,
2. Keeping `KernelAbstractions.Backend` as is but define a new array type, e.g. `NetworkStaticArray`.

If we opt for the latter the array type would look something like: 
```julia
struct NetworkStaticArray{T, AT <: MArray{T}} <: AbstractArray{T}
    A::AT
end
```

I think the second option is more reasonable.

**Comment by michakraus** [comment]
Defining a custom wrapper around `MArray` seems a bit over the top, especially given the potentially very large number of functions you'd have to wrap for this to work properly and as efficiently as `MArray`.

**Comment by benedict-96** [comment]
Ok, then I'll just do 
`const NetworkBackend = Union{KernelAbstractions.Backend, CPUStatic}` and export this :+1:

**Pull request merged**
